### ISSUE TITLE
PodControl/ServiceControl interfaces are duplicated with the JobController create/delete Pod/Service Interface

### ISSUE THREAD

**Issue by jian-he** [kubeflow/common#33]
https://github.com/kubeflow/common/blob/master/job_controller/job_controller.go#L68-L77
https://github.com/kubeflow/common/blob/master/job_controller/job_controller.go#L111-L114

Problem
Above two interfaces are both used for underlying create/delete Pod/Service implementations, which are duplicated.  

Goal
- we should keep one of them
- only in one place, i.e. ControllerInterface.

Solution
1)   Originally thought we can remove the Pod/ServiceControl interface, but there are some code relying on it like [here](https://github.com/kubeflow/common/blob/master/job_controller/pod.go#L226) used for the parameter.  - we could rewrite these to remove the dependency though

2) Keep the Pod/Service Interface, and move it to one place , i.e. the ControllerInterface. I also realized some implementations are directly copied from Kubernetes [utils](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go#L520), wondering why not just use that. 

opinions?
@richardsliu @gaocegege @terrytangyuan

**Comment by johnugeorge** [comment]
Have we moved entire PodControl/ServiceControl logic to JobController?  If we have abstracted PodControl/ServiceControl logic  inside CreatePod/CreateService  and DeletePod/DeleteService of JobController, i think that we won't need https://github.com/kubeflow/common/blob/master/job_controller/job_controller.go#L111-L114

**Comment by terrytangyuan** [comment]
I am fine with keeping one of them as long as the code can be refactored into one place. We could definitely just reuse Kubernetes utils if we are sure those are exact and unnecessary copies.

**Comment by richardsliu** [comment]
Let's try to keep the interface in one place. The internal code structure can always be refactored later, but we should keep the interface stable.

@gaocegege Do you remember why the k8s utils were copied?

**Comment by gaocegege** [comment]
@richardsliu @jian-he @johnugeorge 

It is a historical problem. In v1alpha2, we(me and @ScorpioCPH ) introduces podcontrol and servicecontrol which are used to CRUD K8s resources. We found that importing the implementation from k8s is not what we want. The vendor dep will be much huger. And k8s does not have service control. 

Thus we copied pod control, and implement service control using the similar interface. I do not think we could reuse the code in k8s now since the code base is still big for the feature. the controller-utils.go is still in controller package.

I recommend eliminating the interface, personally.
